#!/usr/bin/env bash

OBSIDIAN_DIR="$HOME/Library/Mobile Documents/iCloud~md~obsidian/Documents/master"

extra_dirs=(
    "$HOME"
    "$HOME/.config/nvim"
    "$OBSIDIAN_DIR"
)

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(
    {
        find ~/projects/work ~/projects/personal -mindepth 0 -maxdepth 1 -type d
        printf '%s\n' "${extra_dirs[@]}"
    } | fzf
)
fi

if [[ -z "$selected" ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s "$selected_name" -c "$selected"
    exit 0
fi

if ! tmux has-session -t="$selected_name" 2> /dev/null; then
    tmux new-session -ds "$selected_name" -c "$selected"
fi

if [[ -z $TMUX ]]; then
    tmux attach-session -t "$selected_name"
else
    tmux switch-client -t "$selected_name"
fi
